name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rust:
    uses: {{ci_owner}}/ci/.github/workflows/rust-ci.yml@{{ci_ref}}
    secrets:
      cargo-registries-polaris-token:          {% raw %}${{ secrets.CARGO_REGISTRIES_POLARIS_TOKEN }}{% endraw %}
      cargo-registries-polaris-internal-token: {% raw %}${{ secrets.CARGO_REGISTRIES_POLARIS_INTERNAL_TOKEN }}{% endraw %}
