name: release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: {{ci_owner}}/ci/.github/workflows/release.yml@{{ci_ref}}
    secrets:
      release-plz-token:                       {% raw %}${{ secrets.RELEASE_PLZ_TOKEN }}{% endraw %}
