name: release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: {{ci_owner}}/ci/.github/workflows/release.yml@{{ci_ref}}
    with:
      publish: {{publish_to_crates_io}}
    secrets:
      release-plz-token:    {% raw %}${{ secrets.RELEASE_PLZ_TOKEN }}{% endraw %}
      cargo-registry-token: {% raw %}${{ secrets.CARGO_REGISTRY_TOKEN }}{% endraw %}
